.PU
.TH wvHtml 1 
.SH NAME
wvHtml \- convert msword documents to html
.SH SYNOPSIS
.ll +8
.B wvHtml [-c charset] [--charset charset] [-p password] [--password password] [-x config.xml] [--config config.xml] filename
.ll -8
.br
.SH DESCRIPTION
.I wvHtml converts word 6, 7 (95) and 8 (97/2000) documents
into html.
.SS OPTIONS
.TP
.I "\-c charset, \-\-charset charset"
word 97 documents are stored in one of two formats, either in 8 bit
windows codepages or in 16bit unicode. The unicode can be converted
easily into utf-8, and the codepages are promoted to unicode and
converted from there, except for the western european codepage
which is always converted to iso-5589-15 if possible. This is the 
default behaviour. It in possible to convert into other formats or to
force a conversion to a particular format, it is not recomended as 
you don't get a guarantee that the output will be correct, for instance if
you convert an english document into koi8-r encoding then it will
be wrong, but if you are sure then you can override the default
output format using this option. The charsets that are available
depend on your system. Systems using the gnu libc 2 and above can
convert to just about anything, systems that at wv configure time prove
to be inadequate for charset conversion use wv's internal conversion
formats which are a small subset of the possible conversions, namely
utf-8
iso-5589-15
koi8-r
tis-620
.TP
.I "\-c password, \-\-password password"
Due to heroic work done by a great team or workers, the wv library can decrypt password protected
word 97 and older versions of word documents given the correct password.
.TP
.I "\-c config.xml, \-\-config config.xml"
Use this to give the location of the config file, if not used the config file is searched for
by first checking the current directory, and then by looking in the install location, by
default its /usr/local/lib/wv/wvHtml.xml
.SH MORE INFORMATION
http://www.csn.ul.ie/~caolan/docs/MSWordView.html
.SH "SEE ALSO"
.BR laola(1), 
.BR lls(1), 
.BR elser(1), 
.BR catdoc(1), 
.BR word2x(1)
.SH "AUTHOR"
 Caolan McNamara 
 WWW: http://www.csn.ul.ie/~caolan/
 Mail: Caolan.McNamara@ul.ie
