.PU
.TH wvHtml 1 
.SH NAME
wvHtml \- convert msword documents to html
.SH SYNOPSIS
.ll +8
.B wvHtml [-c charset] [--charset charset] filename
.ll -8
.br
.SH DESCRIPTION
.I wvHtml converts word 6, 7 (95) and 8 (97/2000) documents
into html.
.SS OPTIONS
.TP
.I "\-c charset, \-\-charset charset"
word documents are stored in one of two formats, either in 8 bit
cp1252 or in 16bit unicode. The 8 bit can be converted easily into
western european iso-5589-15, while the unicode can be converted
easily into utf-8. These are the defaults. It in possible to
convert into other formats, it is not reccomended as you don't
get a guarantee that the output will be correct, for instance if
you convert an english document into koi8-r encoding then it will
be wrong, but if you are sure then you can override the default
output format using this option. The charsets that are available
for output are
utf-8
iso-5589-15
koi-8
.SH MORE INFORMATION
http://www.csn.ul.ie/~caolan/docs/MSWordView.html
.SH "SEE ALSO"
.BR laola(1), 
.BR lls(1), 
.BR elser(1), 
.BR catdoc(1), 
.BR word2x(1)
.SH "AUTHOR"
 Caolan McNamara 
 WWW: http://www.csn.ul.ie/~caolan/
 Mail: Caolan.McNamara@ul.ie
