# Generated automatically from Makefile.in by configure.
CC = gcc
OBJEXT = o

LEX = @LEX@

SHELL=/bin/sh



srcdir=.

CFLAGS = -I/usr/X11R6/include/X11/magick/ -O2 -m486 -fno-strength-reduce -O2   -I/usr/X11R6/include/X11 -DHAVE_CONFIG_H -I$(srcdir)/ -I$(srcdir)/.. -I$(srcdir)/../glib-wv/

SHELL = /bin/sh

.SUFFIXES: .C .$(OBJEXT)

MYOBJECTS =  ms-ole.$(OBJEXT)

all: $(MYOBJECTS) 

ms-ole.$(OBJEXT): $(srcdir)/ms-ole.c 
	$(CC) $(CFLAGS) -c $(srcdir)/$*.c 

clean:	
	rm -rf $(MYOBJECTS) core 

realclean:  
	rm -rf config.cache config.status config.log Makefile *.$(OBJEXT) core demo

#  DO  NOT  DELETE THIS LINE -- make depend depends on it.
