item->istd = read_16ubit(fd);
item->jc = getc(fd);
item->fKeep = getc(fd);
item->fKeepFollow = getc(fd);
item->fPageBreakBefore = getc(fd);
temp8 = getc(fd);
item->fBrLnAbove = (temp8 & 0x01);
item->fBrLnBelow = (temp8 & 0x02) >> 1;
item->fUnused = (temp8 & 0x06) >> 2;
item->pcVert = (temp8 & 0x30) >> 4;
item->pcHorz = (temp8 & 0xC0) >> 6;
item->brcp = getc(fd);
item->brcl = getc(fd);
item->reserved1 = getc(fd);
item->ilvl = getc(fd);
item->fNoLnn = getc(fd);
item->ilfo = (S16)read_16ubit(fd);
item->nLvlAnm = getc(fd);
item->reserved2 = getc(fd);
item->fSideBySide = getc(fd);
item->reserved3 = getc(fd);
item->fNoAutoHyph = getc(fd);
item->fWidowControl = getc(fd);
item->dxaRight = (S32)read_32ubit(fd);
item->dxaLeft = (S32)read_32ubit(fd);
item->dxaLeft1 = (S32)read_32ubit(fd);
wvGetLSPD(&(item->lspd),fd);
item->dyaBefore = read_32ubit(fd);
item->dyaAfter = read_32ubit(fd);
wvGetPHE(&(item->phe),fd);
item->fCrLf = getc(fd);
item->fUsePgsuSettings = getc(fd);
item->fAdjustRight = getc(fd);
item->reserved4 = getc(fd);
item->fKinsoku = getc(fd);
item->fWordWrap = getc(fd);
item->fOverflowPunct = getc(fd);
item->fTopLinePunct = getc(fd);
item->fAutoSpaceDE = getc(fd);
item->fAtuoSpaceDN = getc(fd);
item->wAlignFont = read_16ubit(fd);
temp16 = read_16ubit(fd);
item->fVertical = (temp16 & 0x0001);
item->fBackward = (temp16 & 0x0002) >> 1;
item->fRotateFont = (temp16 & 0x0004) >> 2;
item->reserved5 = (temp16 & ) >> 3;
item->reserved6 = read_16ubit(fd);
item->fInTable = (S8)getc(fd);
item->fTtp = (S8)getc(fd);
item->wr = getc(fd);
item->fLocked = getc(fd);
wvGet*TAP*(&(item->ptap),fd);
item->dxaAbs = (S32)read_32ubit(fd);
item->dyaAbs = (S32)read_32ubit(fd);
item->dxaWidth = (S32)read_32ubit(fd);
wvGetBRC(&(item->brcTop),fd);
wvGetBRC(&(item->brcLeft),fd);
wvGetBRC(&(item->brcBottom),fd);
wvGetBRC(&(item->brcRight),fd);
wvGetBRC(&(item->brcBetween),fd);
wvGetBRC(&(item->brcBar),fd);
item->dxaFromText = (S32)read_32ubit(fd);
item->dyaFromText = (S32)read_32ubit(fd);
temp16 = read_16ubit(fd);
item->dyaHeight = (temp16 & 0x7FFF);
item->fMinHeight = (temp16 & 0x8000) >> 15;
wvGetSHD(&(item->shd),fd);
wvGetDCS(&(item->dcs),fd);
item->lvl = (S8)getc(fd);
item->fNumRMIns = (S8)getc(fd);
wvGetANLD(&(item->anld),fd);
item->fPropRMark = (S16)read_16ubit(fd);
item->ibstPropRMark = (S16)read_16ubit(fd);
wvGetDTTM(&(item->dttmPropRMark),fd);
wvGetNUMRM(&(item->numrm),fd);
item->itbdMac = (S16)read_16ubit(fd);
item->rgdxaTab[itbdMax] = (S16)read_16ubit(fd);
item->rgtbd[itbdMax] = (S8)getc(fd);
