# Generated automatically from Makefile.in by configure.
CC = gcc
OBJEXT = o

SHELL=/bin/sh



srcdir=.

CFLAGS = -I/usr/X11R6/include/X11/magick/ -O2 -m486 -fno-strength-reduce -O2   -I/usr/X11R6/include/X11 -DHAVE_CONFIG_H -I$(srcdir)/

SHELL = /bin/sh

.SUFFIXES: .C .$(OBJEXT)
:g/\.0/s//\.$(OBJEXT)/g


MYOBJECTS = garray.$(OBJEXT) glist.$(OBJEXT) gmem.$(OBJEXT) gmessages.$(OBJEXT) gslist.$(OBJEXT) gstrfuncs.$(OBJEXT) gtree.$(OBJEXT) 

all: $(MYOBJECTS) 

clean:	
	rm -rf $(MYOBJECTS) core 

realclean:  
	rm -rf config.cache config.status config.log Makefile *.$(OBJEXT) core demo

#  DO  NOT  DELETE THIS LINE -- make depend depends on it.
