#!/bin/sh
#
#	Small script to convert the word document to HTML and display 
# 	the output in a browser window

OUTPUT_FILE=/tmp/worddoc.html ;

# Check the input parameter
if [ $# -ne "1" ]; then
	echo "<html><body><H2>Error : Word document not specified</H2></body></html>" > $OUTPUT_FILE
else
	wvHtml $1 $OUTPUT_FILE
fi

netscape -remote 'openFile(/tmp/worddoc.html)'