#!/bin/sh
# This file should be called $HOME/bin/mswordviewsh
# It is meant to be called from within Netscape Mail (when clicking on an
# attachment that's a Microsoft Word version 8 document).
# If you have the mswordview program installed locally, then either modify
# or remove the PATH= statement. If you're using the /freeware version, then
# the statement is required as the mswordview program calls another freeware
# utility.
# In order for netscape to be be aware of the script, you need to edit your
# netscape preferences: expand navigator and select Applications and go down
# to 'Microsoft Word Document' press the edit button and then press the
# Application: radio button and fill in the field with:
# $HOME/bin/mswordviewsh %s
# In order to be able to "click" on the word 8 attachment, you will need to
# select within netscape mail from the "View" pull-down Attachments -> As Links
# vs. Inline

#this came from saggerer@zk3.dec.com

export PATH

PATH=$PATH:/freeware/bin

umask 077

DOC=$1

wvWare $DOC > $DOC.html

netscape -remote "openURL(file:$DOC.html)"

sleep 5

rm $DOC.html
