#!/bin/sh
#from mswordview mailing list by
#E. Frank Ball <frankb@sr.hp.com>
# Modified by Dom Lachowicz Sept 19,2000

htmlfile=/tmp/mswordviewfile$$
wvHtml $1 $htmlfile
lynx -dump -force_html $htmlfile
/bin/rm $htmlfile
